ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
	DECLARE RENTS_NO, DAYS, B_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
	DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED=1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
	FETCH ALL_BOOKS INTO B_ID;
        IF (FINISHED = 0) THEN
			SELECT COUNT(*) FROM RENTS 
				WHERE BOOK_ID = B_ID AND DATEDIFF(CURDATE(), RENT_DATE) < 30 
					INTO RENTS_NO;
            UPDATE BOOKS SET BESTSELLER = RENTS_NO > 2;
		END IF;
	END WHILE;
	CLOSE ALL_BOOKS;    
END $$

DELIMITER ;